<?php

namespace HomeBundle\Repository;

/**
 * RentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RentRepository extends \Doctrine\ORM\EntityRepository
{
}
