course_index:
    path:     /
    defaults: { _controller: "CabBundle:Course:index" }
    methods:  GET

course_show:
    path:     /{id}/show
    defaults: { _controller: "CabBundle:Course:show" }
    methods:  GET

course_new:
    path:     /new
    defaults: { _controller: "CabBundle:Course:new" }
    methods:  [GET, POST]

course_edit:
    path:     /{id}/edit
    defaults: { _controller: "CabBundle:Course:edit" }
    methods:  [GET, POST]

course_delete:
    path:     /{id}/delete
    defaults: { _controller: "CabBundle:Course:delete" }
    methods:  DELETE

course_join:
    path:   /{id}/join
    defaults: { _controller: "CabBundle:Course:join" }
    methods:  [GET, POST]