fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix:   /{_locale}
    requirements:
        _locale: "%app.locales%"

app:
    resource: "@AppBundle/Resources/config/routing.yml"
    prefix:   /
