UserBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO