UserBundle\Entity\User:
    type: entity
    table: fos_user
    repositoryClass: UserBundle\Repository\UserRepository
    id:
        id:
            type: integer
            generator:
                strategy: AUTO
    fields:
        lastname:
            type: string
            length: 255
        firstname:
            type: string
            length: 255
        whatsapp:
            type: string
            length: 14
    manyToMany:
        trips:
            targetEntity: CabBundle\Entity\Course
            mappedBy: users

