<?php

namespace ServiceBundle\Repository;

/**
 * PriceRangeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PriceRangeRepository extends \Doctrine\ORM\EntityRepository
{
}
