<?php

namespace CabBundle\Repository;

/**
 * CabDriverRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CabDriverRepository extends \Doctrine\ORM\EntityRepository
{
}
