app_redirect:
    path:     /
    defaults: { _controller: AppBundle:Main:redirect }

app_homepage:
    path:     /{_locale}
    defaults: { _controller: AppBundle:Main:index }
    requirements:
      _locale: '%app.locales%'