HomeBundle\Entity\OwnerType:
    type: entity
    table: null
    repositoryClass: HomeBundle\Repository\OwnerTypeRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        title:
            type: string
            length: 255
    manyToOne:
        rent:
            targetEntity: HomeBundle\Entity\Rent
            joinColumn:
                name: rentId
                referencedColumnName: id
    lifecycleCallbacks: {  }
