HomeBundle\Entity\Rent:
    type: entity
    table: null
    repositoryClass: HomeBundle\Repository\RentRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        name:
            type: string
            length: 255
        address:
            type: string
            length: 255
        email:
            type: string
            length: 255
        houseFeedback:
            type: text
        ownerFeedback:
            type: text
        size:
            type: integer
        extra:
            type: string
            length: 255
        english:
            type: boolean
    lifecycleCallbacks: {  }
